version: '3.2'

services:
  php:
    container_name: php_car
    build: docker/php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    hostname: localhost
    ports:
      - 9000:9000
    networks:
      - localhost

  nginx:
    container_name: nginx_car
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 8080:8080
    links:
      - php
    networks:
      - localhost

networks:
  localhost: